### ISSUE TITLE
Specific app icon

### ISSUE THREAD

**Issue by blizzz** [nextcloud/sharepoint#1]
Dear @nextcloud/designers may I kindly ask whether one of you would create a nice logo for this app? You can find the [official SharePoint logo on Wikipedia](https://en.wikipedia.org/wiki/File:SharePoint2013Logo.png) as stimulus (although as png).

**Comment by Espina2** [comment]
@blizzz why not use the logo of sharepoint itself?

**Comment by jancborchardt** [comment]
@Espina2 want to do it? :) It needs to be a white svg of 32*32px called app.svg inside the img folder. And make sure to compress it (you can use the scour command of the image-optimization.sh script). Thanks!

**Comment by Espina2** [comment]
@blizzz @jancborchardt 
Its here, I used the svgo to optimize, since I don't have the project installed feel free to optimize further. 
https://cloud.paulomoura.com.pt/owncloud/index.php/s/BL4cMT50EDFOFNk

**Comment by MorrisJobke** [comment]
> @blizzz why not use the logo of sharepoint itself?

Maybe there are copyright issues?

**Comment by Espina2** [comment]
I don't think so. We are not using for commercial or marketing purposes.

**Comment by jancborchardt** [comment]
@Espina2 the problem with svgo is that in some cases it destroys the image. We have a huge problem with that with lots of icons :/ See https://github.com/nextcloud/server/issues/4076

**Comment by jancborchardt** [comment]
Pull request at https://github.com/nextcloud/sharepoint/pull/2

**Comment by Espina2** [comment]
@jancborchardt Most of the times I used the https://jakearchibald.github.io/svgomg/ so I can see the final output. :)
