### ISSUE TITLE
I really cant find the settings menu

### ISSUE THREAD

**Issue by Trauni** [nextcloud/sharepoint#139]
### Steps to reproduce
1. installed nextcloud 24.0.1
2. installed the app Sharepoint Backend
3. Cant find any settings menu

**Comment by blizzz** [comment]
Go to settings → external storages. There you can add your connection,

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/

**Comment by Trauni** [comment]
Thanks - Its very important you mention "External Storage Plugin must be active" as it was not active in my installation. 

Is there anywhere a guide for Office365 Sharepoint connections? (What to fill in the server and document libary fields etc.)
