### ISSUE TITLE
Release sharepoint for Nextcloud 25

### ISSUE THREAD

**Issue by PVince81** [nextcloud/sharepoint#151]
@blizzz I heard there's quite some challenge for testing nowadays ?

**Comment by blizzz** [comment]
Genereting dev instances on microsoft is broken for some time

**Comment by reidatlokbok** [comment]
authentication succeeds but no files listed on nextcloud 25

**Comment by pktiuk** [comment]
Is there any ETA for this task?    
Can it be expected soon or rather later in this year?

**Comment by blizzz** [comment]
Aiming for releases rather this then next week, but eventually it's done when it is done ;)

**Comment by blizzz** [comment]
releases are out
