### ISSUE TITLE
Unable to connect to SharePoint site

### ISSUE THREAD

**Issue by tom-cc** [nextcloud/sharepoint#185]
Hi, I cannot manage to connect to SharePoint to NextCloud. I've follow all the provided instructions and I'm admin on both systems. While doing the configuration, after installing the External Storage Support app, I cannot get it to connect.

I'm using the following params:
Storage Type: SharePoint
Authentication: Username and Password - I'm filling this with the correct credentials that have access to the site I'm trying to connect
Host: the site url as per this pattern "https://yoursitenamehere.sharepoint.com/sites/yoursubsitenamehere"
Document Library: Documents

### Expected behaviour
I'm expecting to be able to establish a connection and get a green checkbox

### Actual behaviour
I get a red icon indicating that the connection as not been successful.

## Server configuration detail

**Operating system:** Linux 5.15.0-76-generic #83-Ubuntu SMP Thu Jun 15 19:16:32 UTC 2023 x86_64

**Webserver:** nginx/1.21.4 (fpm-fcgi)

**Database:** mysql 10.5.22

**PHP version:** 8.2.11

Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, session, PDO, pdo_sqlite, standard, posix, random, readline, Reflection, Phar, SimpleXML, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, apcu, bcmath, exif, gd, gmp, imagick, imap, intl, ldap, maxminddb, memcached, mysqli, pcntl, pdo_mysql, pdo_pgsql, redis, smbclient, sodium, sysvsem, zip, libsmbclient, Zend OPcache

**Nextcloud version:** 27.1.2 - 27.1.2.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

[]
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.19.0
 - bruteforcesettings: 2.7.0
 - circles: 27.0.1
 - cloud_federation_api: 1.10.0
 - comments: 1.17.0
 - contacts: 5.4.2
 - contactsinteraction: 1.8.0
 - dashboard: 7.7.0
 - dav: 1.27.0
 - federatedfilesharing: 1.17.0
 - federation: 1.17.0
 - files: 1.22.0
 - files_external: 1.19.0
 - files_pdfviewer: 2.8.0
 - files_reminders: 1.0.0
 - files_rightclick: 1.6.0
 - files_sharing: 1.19.0
 - files_trashbin: 1.17.0
 - files_versions: 1.20.0
 - firstrunwizard: 2.16.0
 - logreader: 2.12.0
 - lookup_server_connector: 1.15.0
 - nextcloud_announcements: 1.16.0
 - notifications: 2.15.0
 - notify_push: 0.6.3
 - oauth2: 1.15.1
 - password_policy: 1.17.0
 - photos: 2.3.0
 - privacy: 1.11.0
 - provisioning_api: 1.17.0
 - recommendations: 1.6.0
 - related_resources: 1.2.0
 - serverinfo_hetzner: 1.18.0
 - settings: 1.9.0
 - sharebymail: 1.17.0
 - sharepoint: 1.15.0
 - support: 1.10.0
 - survey_client: 1.15.0
 - suspicious_login: 5.0.0
 - systemtags: 1.17.0
 - text: 3.8.0
 - theming: 2.2.0
 - twofactor_backupcodes: 1.16.0
 - twofactor_totp: 9.0.0
 - updatenotification: 1.17.0
 - user_status: 1.7.0
 - viewer: 2.1.0
 - workflowengine: 2.9.0
Disabled:
 - admin_audit
 - encryption
 - user_ldap
 - weather_status: 1.4.0

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "skeletondirectory": "\/var\/www\/html\/themes\/hetzner\/skeleton",
    "simpleSignUpLink.shown": false,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "appstoreurl": "https:\/\/apps.your-storageshare.de",
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "files_external_allow_create_new_local": false,
    "loglevel": 2,
    "log_type": "syslog",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "27.1.2.1",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "default_language": "en",
    "default_locale": "en",
    "default_phone_region": "US",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "syslog_tag": "***REMOVED SENSITIVE VALUE***",
    "upgrade.disable-web": true,
    "updatechecker": false,
    "theme": "hetzner",
    "templatedirectory": "\/var\/www\/html\/core\/skeleton\/Templates\/",
    "enabledPreviewProviders": [
        "OC\\Preview\\PNG",
        "OC\\Preview\\JPEG",
        "OC\\Preview\\GIF",
        "OC\\Preview\\BMP",
        "OC\\Preview\\XBitmap",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown",
        "OC\\Preview\\OpenDocument",
        "OC\\Preview\\Krita",
        "OC\\Preview\\HEIC"
    ],
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": "6379",
        "timeout": "1.5",
        "dbindex": "0"
    },
    "filelocking.enabled": true,
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "updater.server.url": "https:\/\/updates.your-storageshare.de",
    "updater.release.channel": "stable",
    "maintenance": false,
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***",
        "***REMOVED SENSITIVE VALUE***"
    ],
    "allow_local_remote_servers": true
}
```
</details>

**Cron Configuration:** Array
(
    [backgroundjobs_mode] => cron
    [lastcron] => 1697717344
)

**External storages:** yes

<details><summary>External storage configuration</summary>

```
+----------+------------------+----------+---------------------+------------------------------------------------------------------------------------------------------------------------------+---------+------------------+-------------------+-------+
| Mount ID | Mount Point      | Storage  | Authentication Type | Configuration                                                                                                                | Options | Applicable Users | Applicable Groups | Type  |
+----------+------------------+----------+---------------------+------------------------------------------------------------------------------------------------------------------------------+---------+------------------+-------------------+-------+
| 2        | /AdditionalSpace | SMB/CIFS | Global credentials  | host: "u370164.your-storagebox.de", share: "backup", root: "", domain: "", show_hidden: false, check_acl: false, timeout: "" |         | All              |                   | Admin |
+----------+------------------+----------+---------------------+------------------------------------------------------------------------------------------------------------------------------+---------+------------------+-------------------+-------+

```
</details>

**Encryption:** no

**User-backends:** 
 * OC\User\Database

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.46

**Comment by blizzz** [comment]
Hi @tom-cc,

thank you for getting in touch, and it's great to know that you're interested in using the app. We're using GitHub for discussions related to the code itself and improving the code. To address your particular request more effectively, we recommend utilising other channels better suited for support.

In light of this, and apparently being a configuration matter, I will be closing your issue here. There are alternative avenues for assistance, for example I can recommend our very active [home-user forum](https://help.nextcloud.com) or the [official support channels](https://nextcloud.com/contact). You'll have access to a more suitable platform to discuss and resolve any concerns you may have. Thanks again!
