### ISSUE TITLE
External SharePoint storage does not work

### ISSUE THREAD

**Issue by lauff** [nextcloud/sharepoint#203]
### Steps to reproduce
1. try to add external SharePoint storage for 
 
`https://xxx.sharepoint.com/sites/eSportRN/Freigegebene Dokumente/Forms/AllItems.aspx`

SharePoint lists the following information for the library:

Name: `Dokumente`
URL: `https://xxx.sharepoint.com/sites/eSportRN/Freigegebene Dokumente/Forms/AllItems.aspx`

2. tried various combinations for "Host" and "Document Library", but no combinations shows files (although receiving green checkmarks)

### Expected behaviour
Tell us what should happen

List the files from the SharePoint document library in the respective NextCloud folder

### Actual behaviour
Tell us what happens instead

No files shown

### Server configuration

**Nextcloud version:** (see Nextcloud admin page)

Nextcloud AIO v8.1.0

Nextcloud Hub 7 (28.0.4)

**Updated from an older Nextcloud/ownCloud or fresh install:**
no

**Where did you install Nextcloud from:**
Docker AIO

**Comment by blizzz** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
