### ISSUE TITLE
Can't connect to SharePoint

### ISSUE THREAD

**Issue by ghost** [nextcloud/sharepoint#21]
### Steps to reproduce
1. I'm trying to connect nextcloud to our SharePoint Server 2013. But in the error log I get the following error message:

> Error: Call to a member function getTimestamp() on null

Config:

Hostname: https://sp.COMPANY.de/
Document Library: /bereiche/MYNAME/TestCloud/ (TestCloud is the document library)

When I use "sp.COMPNAY.de:443" as hostname I get the following error message:

> Error	core	Exception while scanning storage "SharePoint::sp.COMPANY:443::Documents::MYUSER": Exception: Recv failure: Connection reset by peer

It's also not working when I use "https://sp.COMPANY.de/bereiche/MYNAME/" or "sp.COMPANY.de:443/bereiche/MYNAME/" as hostname.

### Server configuration

**Operating system**: Ubuntu Server

**Nextcloud version:** 13.0.8

**Comment by lucahunziker** [comment]
Hi, I have the same issue:

![immagine](https://user-images.githubusercontent.com/45692570/49655027-b7e33200-fa39-11e8-917b-0555856e31a2.png)

URL: https://mysharepointurl.com/projekte/K_L-GEI/Doks/Forms/AllItems.aspx

Host: https://mysharepointurl.com/projekte/K_L-GEI
Document Library: Doks

NextCloud version: 13.0.7 installed with Univention

Any hint? Thanks

**Comment by blizzz** [comment]
the original issue was fixed meanwhile
