### ISSUE TITLE
Php 7.3 Kali Arm64 + Sharepoint = Destroyed NC 

### ISSUE THREAD

**Issue by tuzohetoruyu** [nextcloud/sharepoint#26]
Php 7.3 Kali Arm64
Crash hole Nextcloud index.php returns after download nothing just blank page 
alltimes

**Comment by odoooooo** [comment]
Same issue here. After downloading and activating the app nextcloud crashes. Blank whithe page and even occ command in cli is working anymore.
To restore my nextcloud instance I have to `rm -r /var/www/nextcloud/apps/sharepoint` .

I am using Ubuntu 18.04, Nextcloud 15, php 7.2.
Should we provide any other information such as log files?

**Comment by blizzz** [comment]
>  Should we provide any other information such as log files?

Yes, ideally fill out the template that is already present when opening an issue, or just grab it from here: https://raw.githubusercontent.com/nextcloud/sharepoint/master/issue_template.md

out of the blue: files_external must be installed first
