### ISSUE TITLE
http problem with connecting to o365 sharepoint

### ISSUE THREAD

**Issue by xXSTrikeXx** [nextcloud/sharepoint#38]
### Steps to reproduce
1. Insert Sharepoint: Domain.de; Folder: /sites/FS/Freigegebene Dokumente/ Userlogin and Password

### Expected behaviour
Should connect to the sharepoint.

### Actual behaviour
Only the red error icon with no notifications about the error.
As admin in the nextcloud.log:

''[sharepoint] Error: Exception: HTTP/2 stream 0 was not closed cleanly: HTTP_1_1_REQUIRED (err 13) at <<closure>>

 0. /var/www/nextcloud/apps/sharepoint/vendor/vgrem/php-spo/src/Runtime/ClientRequest.php line 108
    Office365\PHP\Client\Runtime\Utilities\Requests::execute(Office365\PHP\Cl ... l})
 1. /var/www/nextcloud/apps/sharepoint/vendor/vgrem/php-spo/src/Runtime/ClientRequest.php line 134
    Office365\PHP\Client\Runtime\ClientRequest->executeQueryDirect(Office365\PHP\Cl ... l})
 2. /var/www/nextcloud/apps/sharepoint/vendor/vgrem/php-spo/src/Runtime/ClientRuntimeContext.php line 129
    Office365\PHP\Client\Runtime\ClientRequest->executeQuery()
 3. /var/www/nextcloud/apps/sharepoint/vendor/vgrem/php-spo/src/SharePoint/ClientContext.php line 83
    Office365\PHP\Client\Runtime\ClientRuntimeContext->executeQuery()
 4. /var/www/nextcloud/apps/sharepoint/lib/Client.php line 454
    Office365\PHP\Client\SharePoint\ClientContext->executeQuery()
 5. /var/www/nextcloud/apps/sharepoint/lib/Client.php line 165
    OCA\SharePoint\Client->loadAndExecute(Office365\PHP\Cl ... l}, "*** sensitive parameter replaced ***")
 6. /var/www/nextcloud/apps/sharepoint/lib/Client.php line 101
    OCA\SharePoint\Client->fetchFolder("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
 7. <<closure>>
    OCA\SharePoint\Client->OCA\SharePoint\{closure}("*** sensitive parameters replaced ***")
 8. /var/www/nextcloud/apps/sharepoint/lib/Client.php line 109
    undefinedundefinedcall_user_func_array(Closure {}, ["*** sensitive  ... "])
 9. /var/www/nextcloud/apps/sharepoint/lib/Storage/Storage.php line 617
    OCA\SharePoint\Client->fetchFileOrFolder("*** sensitive parameter replaced ***")
10. /var/www/nextcloud/apps/sharepoint/lib/Storage/Storage.php line 200
    OCA\SharePoint\Storage\Storage->getFileOrFolder("*** sensitive parameter replaced ***")
11. /var/www/nextcloud/lib/private/Files/Storage/Common.php line 452
    OCA\SharePoint\Storage\Storage->stat("")
12. /var/www/nextcloud/apps/files_external/lib/config.php line 269
    OC\Files\Storage\Common->test("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
13. /var/www/nextcloud/apps/files_external/lib/Controller/StoragesController.php line 256
    OC_Mount_Config::getBackendStatus("*** sensitive parameters replaced ***")
14. /var/www/nextcloud/apps/files_external/lib/Controller/UserStoragesController.php line 207
    OCA\Files_External\Controller\StoragesController->updateStorageStatus("*** sensitive parameters replaced ***")
15. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 166
    OCA\Files_External\Controller\UserStoragesController->update("*** sensitive parameters replaced ***")
16. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Files_Extern ... {}, "update")
17. /var/www/nextcloud/lib/private/AppFramework/App.php line 126
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Files_Extern ... {}, "update")
18. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\Files_Exte ... r", "update", OC\AppFramework\ ... {}, {id: "17",_route ... "})
19. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({id: "17",_route ... "})
20. /var/www/nextcloud/lib/private/Route/Router.php line 297
    undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {id: "17",_route ... "})
21. /var/www/nextcloud/lib/base.php line 975
    OC\Route\Router->match("/apps/files_external/userstorages/17")
22. /var/www/nextcloud/index.php line 42
    OC::handleRequest()

PUT /nextcloud/apps/files_external/userstorages/17
''

### Server configuration

**Operating system**:
Raspian
**Web server:**
 Apache/2.4.37 (Raspbian)
**Database:**
mysql
**PHP version:**
PHP Version 7.2.15-1
**Nextcloud version:** (see Nextcloud admin page)
16.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:**
16.0.1
**Where did you install Nextcloud from:**
nextcloud.com

**Comment by blizzz** [comment]
seems to be related to HTTP/2.

**Comment by xXSTrikeXx** [comment]
sudo a2dismod http2
Module http2 already disabled

How can i solve it?

**Comment by blizzz** [comment]
SharePoint Online/365 support was added with the latest release today
