### ISSUE TITLE
Sharepoint Office365

### ISSUE THREAD

**Issue by PLCarl** [nextcloud/sharepoint#41]
Sharepoint Plugin is not working on subsites in 365.

I've configured it to connect and green tick, but am unable to do anything more, as per the fix in issue #7

Error logs are:

![image](https://user-images.githubusercontent.com/41123244/66402031-0c4d9a00-e9dc-11e9-9a88-a1b8e11d0a55.png)

I can confirm that I do have correct rights to this site, and can edit in the SharePoint.

**Comment by blizzz** [comment]
Auth methods needed for SP365 are not supported as of now. Closing as dup of #7.
