### ISSUE TITLE
Error in module version 13.0+

### ISSUE THREAD

**Issue by zmeygarinich** [nextcloud/sharepoint#43]
Good day! Faced the problem of the inability to add Sharepoint libraries on software older than version 1.3.0. Accordingly, I can’t update our server and have to use version 15.x. There is an error on any of the versions: Exception: Cannot find resource for the request ListItemAllFields.
Tested on several libraries and servers Sharepoint versions 2013 and 2016.
Full error log:
{"reqId": "0rPYpjDlUsvaUFjBoPCr", "level": 4, "time": "2019-12-14T15: 47: 11 + 01: 00", "remoteAddr": "IP-Address", "user": " adm "," app ":" webdav "," method ":" PROPFIND "," url ":" \ / remote.php \ / dav \ / files \ / adm \ / test "," message ": {" Exception ":" Exception "," Message ":" Cannot find resource for the request ListItemAllFields. "," Code ": 0," Trace ": [{" file ":" \ / var \ / www \ / nextcloud \ / apps \ / sharepoint \ / vendor \ / vgrem \ / php-spo \ / src \ / Runtime \ /ClientRequest.php "," line ": 138," function ":" validateResponse "," class ":" Office365 \\ PHP \\ Client \\ Runtime \\ ClientRequest "," type ":" -> "," args ": [" {\ "error \": {\ "code \": \ "- 1, Microsoft.SharePoint.Client .ResourceNotFoundException \ ", \" message \ ": {\" lang \ ": \" en-US \ ", \" value \ ": \" Cannot find resource for the request ListItemAllFields. \ "}}}"]} , {"file": "\ / var \ / www \ / nextcloud \ / apps \ / sharepoint \ / vendor \ / vgrem \ / php-spo \ / src \ / Runtime \ /ClientRuntimeContext.php", "line": 129, "function": "executeQuery", "class": "Office365 \\ PHP \\ Client \\ Runtime \\ ClientRequest", "type": "->", "args": []}, {"file ":" \ / var \ / www \ / nextc loud \ / apps \ / sharepoint \ / vendor \ / vgrem \ / php-spo \ / src \ / SharePoint \ /ClientContext.php "," line ": 83," function ":" executeQuery "," class ":" Office365 \\ PHP \\ Client \\ Runtime \\ ClientRuntimeContext "," type ":" -> "," args ": []}, {" file ":" \ / var \ / www \ / nextcloud \ / apps \ / sharepoint \ / lib \ /Client.php "," line ": 454," function ":" executeQuery "," class ":" Office365 \\ PHP \\ Client \\ SharePoint \\ ClientContext "," type " : "->", "args": []}, {"file": "\ / var \ / www \ / nextcloud \ / apps \ / sharepoint \ / lib \ /Client.php", "line": 400 , "function": "loadAndExecute", "class": "OCA \\ SharePoint \\ Client", "type": "->", "args": [{"EntityName": null, "__ class __": "Office365 \\ PHP \\ Client \\ SharePoint \\ ListItem "}, [" Id "]]}, {" file ":" \ / var \ / www \ / nextcloud \ / apps \ / sharepoint \ / lib \ / Storage \ /Storage.php "," line ": 177," function ":" isHidden "," class ":" OCA \\ SharePoint \\ Client "," type ":" -> "," args ": [{ "EntityName": null, "__ class __": "Office365 \\ PHP \\ Client \\ SharePoint \\ Folder"}]}, {"file": "\ / var \ / www \ / nextcloud \ / lib \ / private \ / Files \ / Storage \ / Wrapper \ /Wrapper.php "," line ": 102," function ":" opendir " , "class": "OCA \\ SharePoint \\ Storage \\ Storage", "type": "->", "args": [""]}, {"file": "\ / var \ / www \ /nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php","line":102,"function":"opendir","class":"OC\\Files\\Storage \\ Wrapper \\ Wrapper "," type ":" -> "," args ": [" "]}, {" file ":" \ / var \ / www \ / nextcloud \ / lib \ / private \ / Files \ / Storage \ / Wrapper \ /Availability.php "," line ": 118," function ":" opendir "," class ":" OC \\ Files \\ Storage \\ Wrapper \\ Wrapper "," type ":" -> "," args ": [" "]}, {" file ":" \ / var \ / www \ / nextcloud \ / lib \ / private \ / Files \ / Storage \ / Wrapper \ / Wrapper .php "," line ": 102," function ":" opendir "," class ":" OC \\ Files \\ Storage \\ Wrapper \\ Availability "," type ":" -> "," args " : [""]}, {"file": "\ / var \ / www \ / nextcloud \ / lib \ / private \ / Files \ / Storage \ / Wrapper \ /Wrapper.php", "line": 102, "function": "opendir", "class": "OC \\ Files \\ Storage \\ Wrapper \\ Wrapper", "type": "->", "args": [""]}, {"file ":" \ / var \ / www \ / nextcloud \ / lib \ / private \ / Files \ / Storage \ / Wrapper \ /Wrapper.php "," line ": 102," function ":" opendir "," class ":" OC \\ Files \\ Storage \\ Wrapper \\ Wrapper "," type ":" -> "," args ": [" "]}, {" file ":" \ / var \ / www \ / nextcloud \ / lib \ / private \ / Files \ / Cache \ /Scanner.php " , "line": 375, "function": "opendir", "class": "OC \\ Files \\ Storage \\ Wrapper \\ Wrapper", "type": "->", "args": [" "]}, {" file ":" \ / var \ / www \ / nextcloud \ / lib \ / private \ / Files \ / Cache \ /Scanner.php "," line ": 426," function ":" getNewChildren "," class ":" OC \\ Files \\ Cache \\ Scanner "," type ":" -> "," args ": [" "]}, {" file ":" \ / var \ / www \ / nextcloud \ / lib \ / private \ / Files \ / Cache \ /Scanner.php "," line ": 406," function ":" handleChildren "," class ":" OC \\ Files \\ Cache \\ Scanner "," type ":" -> "," args ": [" ", false, 3,193, true, 0]}, {" file ":" \ / var \ / www \ / nextcloud \ / lib \ / private \ / Files \ / Cache \ /Scanner.php "," line ": 338," function ":" scanChildren "," class ":" OC \\ Files \\ Cache \\ Scanner "," type ":" -> "," args ": [" ", false, 3,193, true]}, {" file ":" \ / var \ / www \ / nextcloud \ / lib \ / private \ / Files \ /View.php " , "line": 1333, "function": "scan", "class": "OC \\ Files \\ Cache \\ Scanner", "type": "->", "args": ["", false ]}, {"file": "\ / var \ / www \ / nextcloud \ / lib \ / private \ / Files \ /View.php", "line": 1377, "function": "get CacheEntry "," class ":" OC \\ Files \\ View "," type ":" -> "," args ": [{" mountPoint ":" \ / adm \ / files \ / test \ / ", "cache": {"__ class __": "OC \\ Files \\ Cache \\ Cache"}, "scanner": {"__ class __": "OC \\ Files \\ Cache \\ Scanner"}, "watcher": null, "propagator": null, "updater": null, "__ class __": "OCA \\ FilesAccessControl \\ StorageWrapper"}, "", "\ / \ / test"]}, {"file": "\ / var \ / www \ / nextcloud \ / apps \ / dav \ / lib \ / Connector \ / Saber \ /Directory.php "," line ": 223," function ":" getFileInfo "," class ":" OC \ \ Files \\ View "," type ":" -> "," args ": [" \ / adm \ / files \ / test "]}, {" file ":" \ / var \ / www \ / nextcloud \ / 3rdparty \ / sabre \ / dav \ / lib \ / DAV \ /Tree.php "," line ": 76," function ":" getChild

**Comment by blizzz** [comment]
I hope to get a new release out, soon(TM).

**Comment by blizzz** [comment]
1.3.1 was release more than a year ago
