### ISSUE TITLE
Sharepoint 2019 support

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/sharepoint#49]
So far, this app only seems to support Sharepoint 2013 and 2016. Since Sharepoint 2019 has been released late 2018 already, more and more people keep asking for this app being supported. Are there plans?

**Comment by blizzz** [comment]
Once we upgrade the sharepoint lib to 2.4 it will probably magically work. No ETA atm.

**Comment by blizzz** [comment]
Already completed
