### ISSUE TITLE
Connecting to Sharepoint Online - Office 365

### ISSUE THREAD

**Issue by pmmgma** [nextcloud/sharepoint#7]
Hi,

I was trying to connect to a SharePoint Site on Office 365 but I faced two problems:

1) There is no documentation about the format of what needs to be added on the fields when adding a SharePoint external storage located, for example, under "/sites" . After a lot of trial-and-error and some deep debug I concluded that:
    **Host:** https://\<tenant\>.sharepoint.com/sites/\<site collection\>
    **Document library:** sites/\<site collection\>/\<document library\>
The "sites/\<site collection\>" must be repeated on the "Document library" field.

2) It was simply not working due to the authentication mechanism of SharePoint Online. I've made the following changes on lib/Client.php to make it work:

        $this->authContext = new AuthenticationContext($this->sharePointUrl);
        $this->authContext->AuthType = CURLAUTH_NTLM;       # Basic auth does not work somehow…
        $this->authContext->acquireTokenForUser($this->credentials['user'], $this->credentials['password']);

        $this->context = new ClientContext($this->sharePointUrl, $this->authContext);

        #$this->authContext = $this->contextsFactory->getAuthContext($this->credentials['user'], $this->credentials['password']);
        #$this->authContext->AuthType = CURLAUTH_NTLM;      # Basic auth does not work somehow…
        #$this->context = $this->contextsFactory->getClientContext($this->sharePointUrl, $this->authContext);

So I've commented the usage of the "contextsFactory" that was leading to "NetworkCredentialContext" and replaced by calls to "AuthenticationContext".
If this kind of authentication needs, of course, to be cleaned up and properly integrated in the remaining code but that's the general idea and for now it's working for me...

Thank you,

Pedro Maia Alves

**Comment by royvanmanen** [comment]
Could not connect to Office365 /sites/doclibrary. Fixed it by modifying as Pedro suggested in Client.php (near the bottom of the file in the ensureConnection function

**Comment by blizzz** [comment]
SharePoint Online/365 support was added with the latest release today

**Comment by digitalgerry2** [comment]
Why is this so badly managed in NextCloud. 
I have tried today using
Domain https://ukfci.sharepoint.com/sites (and also without)
Documents sites// sites/ documents
NLM on and off

I get green with some combo but not seeing the sharepoints I expect to.
Can anyone help
Thanks
Gerry

**Comment by HermannSteier** [comment]
Try
Domain https://ukfci.sharepoint.com
Documentlibrary Documents
NLM off
That worked for me.

**Comment by oscarchd** [comment]
Domain: https://example.sharepoint.com/sites/sitename
Document Library: Documents
NLM off
Username and password have site admin permission

not working

**Comment by HermannSteier** [comment]
Have you tried without the path /sites/sitename ?

**Comment by oscarchd** [comment]
> Have you tried without the path /sites/sitename ?

yup, also not working
