### ISSUE TITLE
Office365 failure

### ISSUE THREAD

**Issue by arduino43** [nextcloud/sharepoint#70]
Hello,

Thanks for the recent update! Unfortunately, I am unable to get this working with Office365.

1.) SharePoint external storage is added and shows green checkmark appears
2.) Nextcloud shows no files found and cannot create files 
3.) sudo -u www-data php occ sharepoint:list-libraries  shows the correct libraries, but shows 0 files for the library I am looking to connect to (Documents)

+---------------------------+-------+-------------------+
| Title                     | Items | Last modification |
+---------------------------+-------+-------------------+
| Documents                 | 0     | 2020-05-09 11:07  |
| Form Templates            | 0     | 2020-05-04 11:27  |
| Site Assets               | 21    | 2020-05-19 02:17  |
| Site Collection Documents | 0     | 2020-05-04 11:27  |
+---------------------------+-------+-------------------+

> {"reqId":"gOoi3tMhnka54BvefMtf","level":3,"time":"2020-05-19T02:41:41+00:00","remoteAddr":"11.22.33.44","user":"admin","app":"text","method":"POST","url":"/index.php/apps/text/session/sync","message":{"Exception":"OCP\\Files\\NotFoundException","Message":"","Code":0,"Trace":[{"file":"/var/www/uploads.myserver.com/apps/text/lib/Service/DocumentService.php","line":363,"function":"getFileById","class":"OCA\\Text\\Service\\DocumentService","type":"->","args":[369,"admin"]},{"file":"/var/www/uploads.myserver.com/apps/text/lib/Service/ApiService.php","line":160,"function":"getFileForSession","class":"OCA\\Text\\Service\\DocumentService","type":"->","args":[{"id":31,"__class__":"OCA\\Text\\Db\\Session"},null]},{"file":"/var/www/uploads.myserver.com/apps/text/lib/Controller/SessionController.php","line":81,"function":"sync","class":"OCA\\Text\\Service\\ApiService","type":"->","args":[369,31,"iExs7SeAG2yIDvtQ82qLpSRKF6qYG6GyURU3N8OMVbpblxqGHu20zNZThd0o2Nmw",0,"",false,true]},{"file":"/var/www/uploads.myserver.com/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"sync","class":"OCA\\Text\\Controller\\SessionController","type":"->","args":[369,31,"iExs7SeAG2yIDvtQ82qLpSRKF6qYG6GyURU3N8OMVbpblxqGHu20zNZThd0o2Nmw",0,"",false,true]},{"file":"/var/www/uploads.myserver.com/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Text\\Controller\\SessionController"},"sync"]},{"file":"/var/www/uploads.myserver.com/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Text\\Controller\\SessionController"},"sync"]},{"file":"/var/www/uploads.myserver.com/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Text\\Controller\\SessionController","sync",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"text.Session.sync"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"text.Session.sync"}]},{"file":"/var/www/uploads.myserver.com/lib/private/Route/Router.php","line":299,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"text.Session.sync"}]},{"file":"/var/www/uploads.myserver.com/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/text/session/sync"]},{"file":"/var/www/uploads.myserver.com/index.php","line":38,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/uploads.myserver.com/apps/text/lib/Service/DocumentService.php","Line":394,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15","version":"18.0.4.2"}

**Comment by blizzz** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
