### ISSUE TITLE
Configuring the Share

### ISSUE THREAD

**Issue by AlexHowser** [nextcloud/sharepoint#8]
Hey! I have installed the SharePoint Backend extension. Since I cant find any Documentation I have a couple of Questions:
How am I supposed to Provide the credentials for the SharePoint Library?
Host: Link to library? wich format?
Document Library, Library Name? ID?
Username, with domain\username username@domain??
It seems like i just dont get this to run, I am using SP 2016 (http) Sites with NTLM, A ubuntu Server in the same IP Segment.

I hope somebody can help me here :slight_smile:
Greetings,
Alex

**Comment by pmmgma** [comment]
On issue #7 I added some hints that I was able to reverse-engineer...

**Comment by AlexHowser** [comment]
Alredy seen and tried, but no effect :/. But thanks for that hard work you did! :)
Am I missing something here? I Use SP2016 on Premise without ssl for now. Do I have to configure something else on SP side? 
I hope @blizzz can help me out here, but it seems like he is not to active lately  :/

**Comment by AlexHowser** [comment]
Allright, i got the soulution. As it turned out my ubuntu server was not able to resolv dns names inside the domain.. I added the search-domain in the interfaces config and everything went well :)

**Comment by blizzz** [comment]
Glad you figured it out  @AlexHowser.

In general what should work is:
* Hostname of the SP server (with port of necessary)
* Document  Library Name
* Username without Domain

As it can be seen on the screenshot.
