### ISSUE TITLE
Could not load storage: "Unable to get backend for sharepoint"

### ISSUE THREAD

**Issue by AlexHowser** [nextcloud/sharepoint#9]
SInce I got the Plugin to work in terms of read access I am still unable to write anything to my SharePoint library :/ The error says: "Internal Server Error" when I try to upload soething and  "Could not load storage: "Unable to get backend for sharepoint"" in Log files.
My user has full access to the SharePoint Library
Greetings,
Alex

**Comment by blizzz** [comment]
@AlexHowser Is it all you see in the logfile? Which Nextcloud and PHP version are you running?

**Comment by AlexHowser** [comment]
PHP Version: 7.0.22

The Unable to get backend for sharepoint seems to show up allmost every second. The webdav exception when i try to upload something, saying that the file i wanted to upload is not existing. The SP User I use got Site Collection Admin rights and got full access to everything, so there shouldnt be anything wrong.

Logfile:

Error | files_external | Could not load storage: "Unable to get backend for sharepoint" | January 19, 2018 10:01:49
-- | -- | -- | --
Error | files_external | Could not load storage: "Unable to get backend for sharepoint" | January 19, 2018 10:01:49
Error | files_external | Could not load storage: "Unable to get backend for sharepoint" | January 19, 2018 10:01:49
Error | files_external | Could not load storage: "Unable to get backend for sharepoint" | January 19, 2018 10:01:49
Error | files_external | Could not load storage: "Unable to get backend for sharepoint" | January 19, 2018 10:01:49
Error | files_external | Could not load storage: "Unable to get backend for sharepoint" | January 19, 2018 10:01:49
Error | files_external | Could not load storage: "Unable to get backend for sharepoint" | January 19, 2018 10:01:48
Error | files_external | Could not load storage: "Unable to get backend for sharepoint" | January 19, 2018 10:01:48
Error | files_external | Could not load storage: "Unable to get backend for sharepoint" | January 19, 2018 10:01:48
Error | files_external | Could not load storage: "Unable to get backend for sharepoint" | January 19, 2018 10:01:48
Error | files_external | Could not load storage: "Unable to get backend for sharepoint" | January 19, 2018 10:01:47
Error | files_external | Could not load storage: "Unable to get backend for sharepoint" | January 19, 2018 10:01:47
Error | files_external | Could not load storage: "Unable to get backend for sharepoint" | January 19, 2018 10:01:44
Error | files_external | Could not load storage: "Unable to get backend for sharepoint" | January 19, 2018 10:01:44
Fatal | webdav | Exception: Die Datei '/websites/ivm/intern/7_IT/02_Anleitungen/ivmRessourcenplanung_Neu_v6.accdb' ist nicht vorhanden. | January 19, 2018 10:01:43
Error | files_external | Could not load storage: "Unable to get backend for sharepoint" | January 19, 2018 10:01:43
Error | files_external | Could not load storage: "Unable to get backend for sharepoint" | January 19, 2018 10:01:43
Error | files_external | Could not load storage: "Unable to get backend for sharepoint" | January 19, 2018 10:01:38

**Comment by AlexHowser** [comment]
Heres the Webdav Error in detail:

Fatal | webdav | Exception: Die Datei '/websites/ivm/intern/7_IT/02_Anleitungen/ivmRessourcenplanung_Neu_v6.accdb' ist nicht vorhanden./var/www/html/nextcloud/apps/sharepoint/vendor/vgrem/php-spo/src/Runtime/ClientRequest.php - line 138: Office365\PHP\Client\Runtime\ClientRequest->validateResponse('{"error" {"code...')/var/www/html/nextcloud/apps/sharepoint/vendor/vgrem/php-spo/src/Runtime/ClientRuntimeContext.php - line 129: Office365\PHP\Client\Runtime\ClientRequest->executeQuery()/var/www/html/nextcloud/apps/sharepoint/vendor/vgrem/php-spo/src/SharePoint/ClientContext.php - line 83: Office365\PHP\Client\Runtime\ClientRuntimeContext->executeQuery()/var/www/html/nextcloud/apps/sharepoint/lib/Client.php - line 399: Office365\PHP\Client\SharePoint\ClientContext->executeQuery()/var/www/html/nextcloud/apps/sharepoint/lib/Client.php - line 126: OCA\SharePoint\Client->loadAndExecute(Object(Office365\PHP\Client\SharePoint\File), Array)/var/www/html/nextcloud/apps/sharepoint/lib/Client.php - line 90: OCA\SharePoint\Client->fetchFile('//websites/ivm/...', Array)[internal function] OCA\SharePoint\Client->OCA\SharePoint\{closure}('//websites/ivm/...', Array)/var/www/html/nextcloud/apps/sharepoint/lib/Client.php - line 99: call_user_func_array(Object(Closure), Array)/var/www/html/nextcloud/apps/sharepoint/lib/Storage/Storage.php - line 597: OCA\SharePoint\Client->fetchFileOrFolder('//websites/ivm/...', Array)/var/www/html/nextcloud/apps/sharepoint/lib/Storage/Storage.php - line 256: OCA\SharePoint\Storage\Storage->getFileOrFolder('//websites/ivm/...')/var/www/html/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php - line 220: OCA\SharePoint\Storage\Storage->file_exists('02_Anleitungen/...')/var/www/html/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php - line 220: OC\Files\Storage\Wrapper\Wrapper->file_exists('02_Anleitungen/...')/var/www/html/nextcloud/lib/private/Files/Storage/Wrapper/Availability.php - line 241: OC\Files\Storage\Wrapper\Wrapper->file_exists('02_Anleitungen/...')/var/www/html/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php - line 220: OC\Files\Storage\Wrapper\Availability->file_exists('02_Anleitungen/...')/var/www/html/nextcloud/lib/private/Files/View.php - line 1330: OC\Files\Storage\Wrapper\Wrapper->file_exists('02_Anleitungen/...')/var/www/html/nextcloud/lib/private/Files/View.php - line 1376: OC\Files\View->getCacheEntry(Object(OCA\Files_Trashbin\Storage), '02_Anleitungen/...', 'IT/02_Anleitung...')/var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/ObjectTree.php - line 160: OC\Files\View->getFileInfo('/ivmadmin/files...')/var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/LockPlugin.php - line 59: OCA\DAV\Connector\Sabre\ObjectTree->getNodeForPath('IT/02_Anleitung...')[internal function] OCA\DAV\Connector\Sabre\LockPlugin->getLock(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/var/www/html/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 466: Sabre\Event\EventEmitter->emit('beforeMethod', Array)/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/var/www/html/nextcloud/apps/dav/appinfo/v1/webdav.php - line 76: Sabre\DAV\Server->exec()/var/www/html/nextcloud/remote.php - line 162: require_once('/var/www/html/n...'){main}
-- | -- | --

**Comment by blizzz** [comment]
Are you running Nextcloud 12? Which exact version? I think the "Could not load storage: "Unable to get backend for sharepoint" message results from there, but it can be ignored… sort of a race condition when initialising the settings of files_external before other storages could have been registered. 

The thrown exception however tells us that a file is not present. I assume after a writing attempt? Is this all you see in the log when you attempt to upload a file?

**Comment by blizzz** [comment]
Oh, and is this againt SP Online?

**Comment by AlexHowser** [comment]
Nextcloud 12.0.4 
SharePoint 2016 on Premise (currrently no SSL) 
Yeah, the webdav error occurs after trying to upload a file into a SP library. 
The log file sadly doesnt provide much more.
I also need to set the Path to the library differently than you pointed out: 
host: http://spserver/websites/sitecollection/
Library: /websites/sitecollection/libraryname
Also I encountered Problems of accessing librarys inside a subsite structure.
Thanks in advance.
Alex

**Comment by AlexHowser** [comment]
I did find some other interesting entrys in the SP ULS Logs: 

01.23.2018   14:03:31.95 | w3wp.exe (0x16C4) | 0x3818 | SharePoint Foundation | Claims Authentication | a5rig | High | User key is not an encoded claim. UserKey:   '            '. | aa54439e-8186-80b5-5706-a12fce57b31e
-- | -- | -- | -- | -- | -- | -- | -- | --
01.23.2018 14:03:31.95 | w3wp.exe (0x16C4) | 0x3818 | SharePoint Foundation | CSOM | apo8x | Medium | The current user 'xxxx' is not in the StackTraceEnabledUsers | aa54439e-8186-80b5-5706-a12fce57b31e

Trying to figure out what it means, but not much luck so far..

**Comment by blizzz** [comment]
Can you verify that NTLM auth is enabled on SP/IIS?

**Comment by AlexHowser** [comment]
Here´s the screenshots from IIS and SharePoint saying that Ntlm is enabled.

IIS:
![image](https://user-images.githubusercontent.com/26967041/35381043-4f950632-01bb-11e8-8a87-774c8ad96668.png)
Sharepoint:
![image](https://user-images.githubusercontent.com/26967041/35381251-f15dbef0-01bb-11e8-9f50-0ab83e379f09.png)
In Central Administration:
![image](https://user-images.githubusercontent.com/26967041/35382499-becfbef8-01bf-11e8-818b-4f9c83cc2274.png)
In the End it turned out, that all Web Apps are configured to run in NTLM-Mode, but the Content Databases are still configured for Windows Classic :/  (Test-SPContentDatabase)
![image](https://user-images.githubusercontent.com/26967041/35383098-9209a54e-01c1-11e8-9747-60aa264b2baa.png)

So it seems like that I have to figure out a way to resolve this before I can go ahead :(
Thanks for your help!

**Comment by lucahunziker** [comment]
Hi @AlexHowser 

I have the same problem. Could you find something?
Thanks

**Comment by AlexHowser** [comment]
hey @lucahunziker !
Nope sorry, I havent had the time to deal with that topic any longer, still hoping for a solution :)

**Comment by blizzz** [comment]
We had issues with localized error messaged from SP. That's solved in the just released versions, and most likely fixes the described issues.
